version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app
  zeitung:
    image: ghcr.io/nycodeghg/zeitung/zeitung
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
    networks:
      - app
    ports:
      - "8080:8080"

networks:
  app:
